Authenticaton Project Review Request
TashfeenRao/members-only pull request #1
Opened 2020-02-21 19:50 UTC by TashfeenRao

2020-02-21 21:18 UTC, samgaco requested changes
Hi @konyan and @TashfeenRao :high_brightness: 

I had the following error when trying to log into your application (after creating a user on the console):

![problemwhenssignin](https://user-images.githubusercontent.com/34820784/75072539-f60e2980-54f7-11ea-9ac7-228001623f92.png)

I also left some comments below that should be addressed.

Good spirit! :muscle: 

-----------------------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2020-02-21 21:18 UTC, samgaco commented on app/helpers/sessions_helper.rb
> +      user = User.find_by(id: user_id)
- [ ] We should have to methods, one to retrieve the current user and another one to set it. [Requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/current_user_requirement.png).

2020-02-21 21:18 UTC, samgaco commented on app/helpers/sessions_helper.rb
> +  end
- [ ] We should have a sign-in method. [Requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_method_requirement.png).

2020-02-21 21:18 UTC, samgaco commented on app/views/layouts/application.html.erb
>  </html>
- [ ] We should have Sign in/Sign out links present in any view of the app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

2020-02-21 21:18 UTC, samgaco commented on config/routes.rb
> +  get '/posts/new', to: 'posts#new'
- [ ] Have this [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) into account.

2020-02-24 22:34 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @TashfeenRao @konyan 

Thank you for the improvements done!
However, there are still things to update

1. Your app lacks navigation. For example, from `Sign In` it's not possible to go back to the list of posts. Another one, once connected, from `posts` there is no link to access to the post creation form. Make sure to simplify the test by implementing a good navigation.

2. There is no user creation form, what is not required and there is no also any indication to how to start using your app. I suggest you update the README with indications on how to start either by creating an user via `rails console` or by using an user you create through `rails db:seed`

3. @samgaco mentionned this https://github.com/TashfeenRao/members-only/pull/1#discussion_r382807836 and you must notice that when implementing it, you no longer need `session`. Try and you will see how `cookies` simplifies your code.

4. Please, read the comments left below.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-02-24 22:34 UTC, maelfosso commented on app/models/user.rb
> +  before_create :remember_token
Please, use two different names. In your case, I think that what comes close to the `before_create` is something between `digest` and `new_token`

2020-02-24 22:34 UTC, maelfosso commented on app/models/user.rb
> +  end
You need to rewrite two 2 methods

`before_create` should only set up `self.remember_token`
You will set up `self.remember_token` with the result of a method which has theses steps
1. Generate a new token
2. Digest the new token and return it.

2020-02-24 22:34 UTC, maelfosso commented on app/models/user.rb
> +  end
If you follow the instructions given up, you will update it with only the last lines

2020-02-25 23:59 UTC, maelfosso requested changes
# Changes required :red_circle: 

Thank you for the improvements!!!
I got a problem when launching the app
![Screenshot_2020-02-26_00-52-19](https://user-images.githubusercontent.com/8848104/75298324-730c0c80-5832-11ea-96ca-09f4319af275.png)

Kindly fix that and submit a new code review request.
Thanks

Mael FOSSO

2020-02-26 17:24 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @TashfeenRao  , 👋 You have done a great job in this project 👏 
- [ ] [ Optional] Pull Request should have a meaningful title and a short description
<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">


----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2020-02-26 19:18 UTC, merged